NumPy, short for Numerical Python, is one of the most important foundational pack‐
ages for numerical computing in Python. Many computational packages providing
scientific functionality use NumPy’s array objects as one of the standard interface
lingua francas for data exchange. Much of the knowledge about NumPy that I cover is
transferable to pandas as well.
Here are some of the things you’ll find in NumPy:
• ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities
• Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops
• Tools for reading/writing array data to disk and working with memory-mapped
files
• Linear algebra, random number generation, and Fourier transform capabilities
• A C API for connecting NumPy with libraries written in C, C++, or FORTRAN

One of the reasons NumPy is so important for numerical computations in Python is
because it is designed for efficiency on large arrays of data. There are a number of
reasons for this:
• NumPy internally stores data in a contiguous block of memory, independent of
other built-in Python objects. NumPy’s library of algorithms written in the C lan‐
guage can operate on this memory without any type checking or other overhead.
NumPy arrays also use much less memory than built-in Python sequences.
• NumPy operations perform complex computations on entire arrays without the
need for Python for loops, which can be slow for large sequences. NumPy is
faster than regular Python code because its C-based algorithms avoid overhead
present with regular interpreted Python code.
NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory.

In [1]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
%timeit my_arr2 = my_arr*2

2.85 ms ± 266 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%timeit my_list2 = [x*2 for x in my_list]

56.5 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## The NumPy ndarray: A Multidimensional Array Object ##
One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

An ndarray is a generic multidimensional container for homogeneous data; that is, all
of the elements must be the same type. Every array has a shape, a tuple indicating the
size of each dimension, and a dtype, an object describing the data type of the array:

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data.ndim

2

### Creating ndarrays ###
The easiest way to create an array is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array
containing the passed data.

Nested sequences, like a list of equal-length lists, will be converted into a multidimen‐
sional array.

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In addition to numpy.array, there are a number of other functions for creating
new arrays. As examples, numpy.zeros and numpy.ones create arrays of 0s or 1s,
respectively, with a given length or shape. numpy.empty creates an array without
initializing its values to any particular value. To create a higher dimensional array
with these methods, pass a tuple for the shape.

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[9.44347077e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.23078064e+160]],

       [[9.51546998e-047, 5.22379456e-037],
        [5.05692611e-038, 1.35109771e+161],
        [1.17426500e+165, 1.60339524e-051]]])

> It’s not safe to assume that numpy.empty will return an array of all
zeros. This function returns uninitialized memory and thus may
contain nonzero “garbage” values. You should use this function
only if you intend to populate the new array with data.

Some important NumPy array creation functions

| Function | Description |
|----------|-------------|
|array|Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default|
|asarray |Convert input to ndarray, but do not copy if the input is already an ndarray |
|arange |Like the built-in range but returns an ndarray instead of a list |
|ones, ones_like |Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces a ones array of the same shape and data type |
|zeros, zeros_like |Like ones and ones_like but producing arrays of 0s instead |
|empty, empty_like |Create new arrays by allocating new memory, but do not populate with any values like ones and zeros |
|full, full_like |Produce an array of the given shape and data type with all values set to the indicated “fill value”; full_like takes another array and produces a filled array of the same shape and data type |
|eye, identity |Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere) |

### Data Types for ndarrays ###

The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data.

![](images/image1.png)
![](images/image2.png)

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

You can explicitly convert or cast an array from one data type to another using ndarray’s **astype** method.

If I cast some floating-point numbers to be of integer data type, the decimal part will be truncated.

In [31]:
int_arr1 = arr1.astype(np.int64)
int_arr1

array([1, 2, 3])

You can also use another array’s dtype attribute

In [32]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

There are shorthand type code strings you can also use to refer to a dtype.

In [33]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays ###